plaintext = "Breath of the Wild is better than Tears of the Kingdom so prove me wrong."
plaintext = list(plaintext)
morse_text = ""
morse_key = {
    " ": "/",
    "a": ".-",
    "A": ".-",
    "b": "-...",
    "B": "-...",
    "c": "-.-.",
    "C": "-.-.",
    "d": "-..",
    "D": "-..",
    "e": ".",
    "E": ".",
    "f": "..-.",
    "F": "..-.",
    "g": "--.",
    "G": "--.",
    "h": "....",
    "H": "....",
    "i": "..",
    "I": "..",
    "j": ".---",
    "J": ".---",
    "k": "-.-",
    "K": "-.-",
    "l": ".-..",
    "L": ".-..",
    "m": "--",
    "M": "--",
    "n": "-.",
    "N": "-.",
    "o": "---",
    "O": "---",
    "p": ".--.",
    "P": ".--.",
    "q": "--.-",
    "Q": "--.-",
    "r": ".-.",
    "R": ".-.",
    "s": "...",
    "S": "...",
    "t": "-",
    "T": "-",
    "u": "..-",
    "U": "..-",
    "v": "...-",
    "V": "...-",
    "w": ".--",
    "W": ".--",
    "x": "-..-",
    "X": "-..-",
    "y": "-.--",
    "Y": "-.--",
    "z": "--..",
    "Z": "--..",
    ".": ".-.-.-"
}

for i in range(len(plaintext)):
    morse_text += " "
    morse_text += morse_key[plaintext[i]]

print(morse_text[1:])
